
#Solução por: Laryssa de Oliveira Ferreira - Engenharia de Computação - UnB

'''Each new term in the Fibonacci sequence is generated by adding the previous two terms.
By starting with 1 and 2, the first 10 terms will be:
1, 2, 3, 5, 8, 13, 21, 34, 55, 89, ...
By considering the terms in the Fibonacci sequence whose values do not exceed four million, find the sum of the even-valued terms.'''


'''para resolver esse problema, devemos:

#1: Criar uma função para a sequência de fibonacci

#2: definir uma variável para receber o valor antigo

#3: definir uma variável para receber o novo valor da sequência de fibonacci

#4: definir o intervalo (4 milhões) em que o programa irá atuar

#5: encontrar os números pares da sequência nesse intervalo

#6: imprimir a soma dos números encontrada

'''
def fibonacci(valor_maximo):
    
    v1 = 1
    
    v2 = 2
    
    termos = [v1, v2] 
    
    while v2 <= valor_maximo:
        
        novo_num = v1 + v2
        
        termos.append(novo_num)
        
        v1 = v2
        
        v2 = novo_num
        
    return termos

termos_seq = fibonacci(4000000)

soma_pares = sum(termo for termo in termos_seq if termo % 2 == 0)

print(soma_pares)

